### ISSUE TITLE
Where is the chatting

### ISSUE THREAD

**Issue by jeffslofish** [lovelle/jquery-chat#1]
I followed your instructions step by step from the README, and the end result is that I get a webpage displayed that says "My website :-)" but there is no chat box or anything. What am I missing?

**Comment by lovelle** [comment]
Hi, Thanks for trying the chat :smiley:. Did you edit the "index.html" and also "config.js" file with the connection to node.js? (remember that if you have it all in localhost like in the examaple then you not need to edit them) but if you try to connect to the chat from another computer, then you must change this values.

what browser and version are you using? what webserver are you using to serve the chat?, the one described in readme (python) or a full web server like apache?.
Would be very helpful if you could provide a print screen (send me in private by email). Also if you could turn on firebug (in firefox) or console debug in chrome would help to see if there is any trouble with javascript or any lib.

**Comment by lovelle** [comment]
I have been experienced this issue in some chrome versions, pretty sure when the next warning is displayed:

> jquery-1.11.0.min.js:4 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

the chat can't be loaded.

I keep searching the best solution for this issue, for now just try another browser and will work.

**Comment by lovelle** [comment]
I tested this issue and seems to be fixed now, please @jeffslofish  update the latest changes on the master branch and tell me if it works now.

Best regards

**Comment by jeffslofish** [comment]
Hi @lovelle. I just got the latest changes and it still doesn't work. I am using WIndows 8 with XAMPP. 

I changed line 5 of config.js to 

```
   server: 'localhost:3000',
```

I changed line 11 of index.html to 

```
    <script src='http://localhost:3000/socket.io/socket.io.js'></script>
```

Now I am not getting any errors in the console, but all I see is "My website :-)"

**Comment by jeffslofish** [comment]
Oh, wait a minute, I think it is working now....it is the bar at the bottom of the screen, right?

**Comment by lovelle** [comment]
Yes :+1:, remember that you could personalize the bar with some custom params in "config.js".
With some of the latest changes pushed at github i have configured the chat to be work with a heroku app, but you could deploy your own node.js app. If you have any questions related to any functionality feel free to send me an email.
