### ISSUE TITLE
Archivo server.js

### ISSUE THREAD

**Issue by Josnic** [lovelle/jquery-chat#12]
Saludos.

Quisiera saber como ejecutar este archivo sin la necesidad del comando node.

**Comment by lovelle** [comment]
No puedes ejecutarlo sin el comando 'node', lo que si puedes es hacer deploy del chat sin la necesidad de un 'node' propio, el chat por defecto se conecta a un node hosteado en heroku, por lo tanto no lo necesitas.
Si lo que quieres es tu propio servidor node en tu red privada, tienes que tener el comando 'node' para poder levantarlo y configurar el cliente para que pueda conectarse a este (editar 'config.js' y los parametros 'server' y 'port' y el archivo 'index.html').

**Comment by Josnic** [comment]
Muchas gracias por tu respuesta. Estoy trabajando en un servidor local y ya cambie los datos de 'server=127.0.0.1' y port='9300'. Sin embargo, quiero que el comando node se ejecute automáticamente una vez el index.html se ejecute. Como puedo crear un debugger para ello.

Agradezco tu colaboración.

**Comment by lovelle** [comment]
Te recomiendo que pongas port='3000' ya que es el puerto por defecto que levanta server.js, sino también tendrás que editar la primera linea de server.js para que escuche en el 9300.

Lo que estas intentando hacer no lo puedes hacer con el archivo "index.html" tal como esta por defecto ya que necesitas hacer esa comprobación o levantar node en el lado del backend.

Lo que podrías hacer es por ejemplo poner un "index.php" que forme el html necesario para que funcione el chat y que compruebe que node esté corriendo en el servidor.

Lo cual podría hacerte las cosas muy complejas y no es necesario tal chequeo, si lo que te preocupa es que se caiga la app de node, lo que te recomiendo es que levantes node con el comando "forever" de nodejs el cual va a levantar el script de forma automática en caso de crash.
Para instalar forever es con: npm install forever --global
y para ejecutarlo entonces tendrías que hacer: forever server.js

En [este sitio](http://qbit.com.mx/blog/2014/02/11/poniendo-en-marcha-un-servidor-de-nodejs-con-forever/) tienes mas info de como hacer funcionar 'forever'

**Comment by Josnic** [comment]
Saludos.

Cambié el puerto a 3000 y ejecute npm start en la consola  de git y funciona perfectamente. Mi pregunta es si al subirlo a un servidor en la nube, como puedo ejecutar el server.js desde un archivo que ejecute el comando 'node' o 'forever' una vez el usuario accede a mi sitio.

Gracias.

**Comment by lovelle** [comment]
Una vez que el usuario accede al index, no es recomendable que este flow "levante" la app de node, lo normal es que ya esté levantada y el cliente únicamente se conecte a este.

El servidor/hosting tiene que permitir poder de hacer deploy de aplicaciones node.js, uno que puedes utilizar para deployar server.js es [heroku](https://www.heroku.com/)

Saludos.

**Comment by Josnic** [comment]
Agradezco su ayuda.

Saludos.

**Comment by lovelle** [comment]
Gracias a usted por usar el chat :+1: 

Saludos!
