### ISSUE TITLE
New Updates Causing problem

### ISSUE THREAD

**Issue by Adnanhmd** [lovelle/jquery-chat#17]
Whenever we clicked on logged in users this error is coming 
Error: Uncaught TypeError: s.slimScroll is not a functionUrl: http://115.119.117.86:8085/home/Maxx/maxxlogin/jquery-chat-master/js/jquery.main.jsLine: 780

**Comment by lovelle** [comment]
Hi
If you are working on master branch add to you index the next line 

``` html
 <script src='js/jquery.slimscroll.min.js'></script>
```

take a look in 'index.html' as an a working example

**Comment by Adnanhmd** [comment]
Thanks Appreciated.

**Comment by lovelle** [comment]
Thanks to you for contribute with the chat.
