### ISSUE TITLE
Avatar Problem

### ISSUE THREAD

**Issue by Adnanhmd** [lovelle/jquery-chat#18]
When we start the conversion the first avatar picture wont be visible. Here is the screen shot.
![issue](https://cloud.githubusercontent.com/assets/13015387/8643194/0a7cf1e2-294e-11e5-9afe-d46ca4168fd0.png)

**Comment by lovelle** [comment]
Hi, sorry for delay, this is not an issue, 

I'm going to explain why: when a user doesn't have a gravatar icon, the logic at server side will return in a randomly way the next list of posibilitys:

``` javascript
var avatar_404 = ['mm', 'identicon', 'monsterid', 'wavatar', 'retro'];
```

the mm is mystery-man (the icon you see) if you want you can take off the 'mm' option in list and thats all.

**Comment by lovelle** [comment]
closing because is not an issue.

Bye.
