### ISSUE TITLE
New feature - allow search button be case sensitive

### ISSUE THREAD

**Issue by Adnanhmd** [lovelle/jquery-chat#20]
Hi

While searching the casing has to be ignored.

**Comment by lovelle** [comment]
Hi, sorry but I dont understand that, you mean you won't the search be case sensitive?.
Please provide more information on what you are attempting to do.

**Comment by Adnanhmd** [comment]
Hi

Let me be more clear, i have a active user called "Alpha". But in search if i type "alpha" it wont show the result. I have to type exact letters like "Alpha" .

**Comment by lovelle** [comment]
Hi
ok, is what I supposed at the beginning, I think would be good to have this behaviour configurable with some param like "search_case_sensitive = true" in config.js.

Please tell me if this make sense to you.

**Comment by Adnanhmd** [comment]
Hi
That also could be fine. If i use "search_case_sensitive = true" in config file. whether it will work for current version ???

**Comment by lovelle** [comment]
Not for now, I'm going to take care of this today so I think it could be done quickly because is not too difficult.

**Comment by lovelle** [comment]
Now, the installation process should be documented.

**Comment by lovelle** [comment]
Done, please update the branch master and change the parameter _search_case_sensitive_ to _false_ value like this

``` javascript
search_case_sensitive: false,
```

in _config.js_

**Comment by lovelle** [comment]
merged.

**Comment by Adnanhmd** [comment]
Thanks appreciated.
