### ISSUE TITLE
Port Issue

### ISSUE THREAD

**Issue by Adnanhmd** [lovelle/jquery-chat#22]
Hi

In config.js i have server: '115.119.117.86',port: '3005',
but no matter whatever the port number i give it takes only 3000 and when i run the server, i get this
node server.js
info  - socket.io started
jqchat listening on ::3000

And in server.js, if i give
var port = 3005; rather then var port = process.env.PORT || 3000; it works fine
 info  - socket.io started
jqchat listening on ::3005

I think in server.js, these snippets  are not working as expected
var port = process.env.PORT || 3000;
server   = require('http').createServer(),
var addr = server.address();

**Comment by lovelle** [comment]
This code works as expected, if you do 

``` javascript
var port = 3005;
```

it works (recently checked), please take a look that you must restart the server node instance to get working these change. So, if you change anything about "server.js" you must stop and start again the server script.
Hope this help.

**Comment by Adnanhmd** [comment]
I have closed command prompt itself and started server again by giving node server.js. But still same result. When i check console.log(addr); this gives the output as { address: '::', family: 'IPv6', port: 3000 }

**Comment by lovelle** [comment]
Here there is just 2 possibilities I think, or you dont really change the value in the 'server.js' script or you don't restart node. I also just check that on heroku and it works fine, sorry but I don't know how to help you if you don't provide something to show or more data.
Bye.

**Comment by Adnanhmd** [comment]
Hi
 I have check with public ip and localhost, it is the same result. I tried with the fresh copy also. Here are the screen shots. Only problem not working in different port. Apart from 3000 
![commandpromt](https://cloud.githubusercontent.com/assets/13015387/8724070/387ac6a4-2bed-11e5-89b8-da4b58e29731.png)
![config](https://cloud.githubusercontent.com/assets/13015387/8724069/387a36a8-2bed-11e5-8be0-a00a0c424f37.png)
![server](https://cloud.githubusercontent.com/assets/13015387/8724072/387d04e6-2bed-11e5-8dc8-6dbddffd3cc0.png)
![socket](https://cloud.githubusercontent.com/assets/13015387/8724071/387cfdde-2bed-11e5-9d3a-f97063ffadcd.png)

**Comment by lovelle** [comment]
Ok, now I understand your confusion about this and what is wrong to change the server port.

I'm going to explain: the _'config.js'_ file is a configuration file **only** for client settings, this configuration file _'config.js'_ don't apply to server setting, so, knowing that, if you want to change the port you must set this in _'config.js'_ (for client connection properly) **and also** in _'server.js'_.

Take a look at 3rd screenshot in line one you have:

``` javascript
var port = process.env.PORT || 3000;
```

and instead of that, you must change it for next one:

``` javascript
var port = process.env.PORT || 3005;
```

restart the node server, and all should work fine.

Hope this may help you.

**Comment by lovelle** [comment]
Due to no response I'm assuming that the issue is solved.

Bye

**Comment by Adnanhmd** [comment]
That worked. Thanks appreciated.
