### ISSUE TITLE
Chat is not connected for many system

### ISSUE THREAD

**Issue by Dinesh1412** [lovelle/jquery-chat#23]
Hi Everyone,
                    I have utilized this Chat Master into my application.I am facing issue while opening my landing page into many systems.This chat is disconnected for many systems and only for few systems only connected.Pls help me to get solution for that.

**Comment by lovelle** [comment]
Hi, sorry for delay.

Thank you for using the chat :smile:
In order to help you to integrate the chat, please I need more details to find out exactly what your problem is. If you could provide some online link or something like that would be very helpful.
Regards.

**Comment by lovelle** [comment]
Closing due to not activity.
