### ISSUE TITLE
Message archive?

### ISSUE THREAD

**Issue by heriniaina** [lovelle/jquery-chat#24]
Hello, 

Is there anyway of keeping the message archive or message log somewhere? To create something like offline message where people can re-read later

**Comment by lovelle** [comment]
Hi, very thanks for using the chat :+1: 

1st if you just want to store the messages as some kind of log, this is very easy to accomplish.
2nd In other way if you want to store messages undelivered to show to the user when will be available is more difficult.

Please let me know what of those features you are trying to get.
I think the 2nd one would great to do it.

**Comment by lovelle** [comment]
Now duplicated, we track this in #34
