### ISSUE TITLE
socket.io version is too lower

### ISSUE THREAD

**Issue by chinavane** [lovelle/jquery-chat#25]
The current version is 1.3.6 socket.io, and the system applied is 0.9, we try to service/client connection appears in the time {"code": 0, "message": "Transport unknown"} error. Access to information on the Internet later said that the reason soekct.io version too lower, and whether you can be about the updated version of the system?

**Comment by lovelle** [comment]
Hi, sorry for delay.

You are totally right, I think i have this pending in my own todo list.
I will take care of these ASAP.

Thanks for reporting.

**Comment by lovelle** [comment]
This is already done in master with version 2.0.3
