### ISSUE TITLE
Theme not loading...

### ISSUE THREAD

**Issue by ferenczAndras** [lovelle/jquery-chat#27]
Hello.
I have a question. Maybe I did something wrong but i downloded the project and installed and this is how it looks like... somehow the theme is not loading or idk. What to do ?

![image](https://cloud.githubusercontent.com/assets/10342283/9694289/e624d3c8-535f-11e5-8126-a24f214f1089.png)

**Comment by HenriqueCRodrigues** [comment]
me too

**Comment by HenriqueCRodrigues** [comment]
@lovelle need help
