### ISSUE TITLE
Group messages

### ISSUE THREAD

**Issue by ferenczAndras** [lovelle/jquery-chat#29]
I just started, to make a new feauture. Group messages. You can create new Groups, and add people on it, and this group is live till somebody is online. If everybody gets off, the group will be deleted automatically. What do you think ?:D

**Comment by lovelle** [comment]
Hi, I think that is a wonderful feature to have!!! Very appreciated :+1:  !!
I'm very curious to see those changes in order to have them, when you finish please do a pull request and I promise to dedicate the time it deserves your feature.

Again, very thank you.
Cheers.

**Comment by celorodovalho** [comment]
+1 for this new feature!
Do you have yet a deadline?
Coz I am in need of this feature and I am thinking of developing it too.

**Comment by lovelle** [comment]
Hi, sorry, but no deadline is defined, I suppose I will do this when I can find some free time.

So the thing is: I think this [issue](https://github.com/lovelle/jquery-chat/issues/25) has more priority, after that, I will do this one.

Deeply sorry for being a non-positive response.
Thanks for interest in the chat :+1: 

Bye
