### ISSUE TITLE
how to limit the chat to one user speaking with server only?

### ISSUE THREAD

**Issue by airport-transfers** [lovelle/jquery-chat#3]
I would like to use jquery-chat for a chatbot, so I will have only 2 users in the chats: HUMAN and ROBOT. Could you please give me some tip to simplify your chat for this scope?

**Comment by lovelle** [comment]
Hello,

can you please elaborate a bit? what thing are you trying to simplify (client or server side)? you want to the HUMAN send messages and the ROBOT re-send what he receive?
Thanks.

**Comment by airport-transfers** [comment]
chatbot

**Comment by lovelle** [comment]
Hi
if you really want this please contact me by email and I can provide you some server example script, this will not be added in main functionality in the chat for compatibility reasons.
Thanks.
