### ISSUE TITLE
How we can save the conversation and resume service  

### ISSUE THREAD

**Issue by sanjaygupta1234** [lovelle/jquery-chat#31]
I want to save conversation  and I want to be able for the user can see their previous chat in system. please help me.

**Comment by ferenczAndras** [comment]
Hy. I suggest to use an ajax post to a php script, where you can save the massage into a mysql database. When you load the chat, you read all the messages from the database, and you are ready to go .

**Comment by sanjaygupta1234** [comment]
Ohh!..thats what I was thinking, I just want to be sure whether it save the chatting some where in files or not. thanks Andras for your response...

**Comment by ferenczAndras** [comment]
I used this chat a lot, and it is a very good one. Probably i will give to lovelle a code snipett with saving the file. Hope it helped you :)

**Comment by lovelle** [comment]
Hi guys :satisfied:

I have just recently push a new file in `server/node/server_redis_storage.js`
As the filename says, is the server implementation but storing users in redis database.
I still need time to do the store of users conversations, I think tomorrow I will do it.

Bye

**Comment by lovelle** [comment]
Done, in `server/node/server_redis_storage.js` chats will be saved in a key like ´jqchat:chats:{user-origin}-{user-dest}`

**Comment by sanjaygupta1234** [comment]
That's cool what are the relative changes we need to do in order to get saved chats, in previous script,  because I have already implemented this on my server so I want to add changes only.

**Comment by lovelle** [comment]
The new chat server that handles the chat store into redis db is based from the original one `server.js`.

So, you can do this in order to see the differences: `diff server.js server_redis_storage.js`

**Comment by lovelle** [comment]
Pending TODO: Add history chat to client chatbox if exist in database.
