### ISSUE TITLE
There is an HOW-TO on to run server in Heroku platform?

### ISSUE THREAD

**Issue by felipe3ds** [lovelle/jquery-chat#35]
Hello lovelle, congrats for your job! its amazing!
I trying to create a server on Heroku... I guess i need some help on that!
there is any tutorial on that?
thanks!

**Comment by lovelle** [comment]
Hi, actually not, I didn't think something like that was necessary.
In fact, is quite easy deploy the chat (server logic) on heroku platform, or, at least, it should be as difficult as to deploy any node app.

You only need to create an app with the script `server/node/server.js` and thats it.
If you are locked with this, please send me an email and I will try to help you to acomplish that.

Bye.
