### ISSUE TITLE
socket.io does not connect

### ISSUE THREAD

**Issue by jterlouw951** [lovelle/jquery-chat#37]
The socket does not connect and the chat window keeps on being on connecting.

I am using SSL
while starting the socket.io I get this error:
   info  - socket.io started
(node:21848) DeprecationWarning: process.EventEmitter is deprecated. Use require
('events') instead.
jqchat listening on ::3000

and network log gives these errors:
https://life.b4all.com/socket.io/?EIO=3&transport=polling&t=LViOQ9g
403 forbidden

Any idea I do wrong?

**Comment by tewemit** [comment]
Hi,
I am having the same issues here. Did you find a way to have it work for you?

**Comment by lovelle** [comment]
Hi, sorry but I never tried this, there is an open issue reporting this and they could finally implement this, please see #34.
Closing because is dup.
