### ISSUE TITLE
Integrate in data base

### ISSUE THREAD

**Issue by sandub** [lovelle/jquery-chat#39]
Hello I am interested to integrate such a chat, a website, and use the database, the site, to keep the user and data authentication. Is it possible to do that? How?

**Comment by svgningke** [comment]
sadedcdsafcae

**Comment by sandub** [comment]
"https://github.com/wumix/Smart-Space" here i want to integrate this chat.

**Comment by lovelle** [comment]
This is already done with redis database as a storga in `server/node/server_redis_storage.js`

Bye.
