### ISSUE TITLE
socket is undefined on https domain

### ISSUE THREAD

**Issue by lalitchamate** [lovelle/jquery-chat#4]
Hello,

Its working on local server like xampp but I am facing some errors on my live domain and Can you please tell me if I have https domain then what changes I have to do in scripts as I am facing some errrors on like socket is undefined.

Thanks

**Comment by lovelle** [comment]
Hello,

if you see error like "socket is undefined" I'm pretty sure that you have not get node server up (Step 3 in Readme). If you get the last commit, the chat is configured to work with heroku app https://jquery-chat.herokuapp.com/socket.io/ so you not need your own node server, but you could have it if you want. Please use the last commit or get up your node server (step 3) with the settings configured in 'config.js' and 'index.html'. 
If the problem persist please let me know.

**Comment by lovelle** [comment]
closed due to no response
