### ISSUE TITLE
Bug Git Clone

### ISSUE THREAD

**Issue by HenriqueCRodrigues** [lovelle/jquery-chat#42]
I did the git clone, but on my local host the bootstrap is buggy
Error Console:
> GET http://localhost/jquery-chat/themes/smoothness/jquery-ui.min.css                    jquery-1.11.3.min.js:5 

Image Error:
`http://imgur.com/a/Zxjb1`
@lovelle help me

**Comment by lovelle** [comment]
This is because css styles are not loaded, please check your domain dns or if you have the link 'themes' to the folder 'jquery-ui-themes-1.10.4/themes/'

Not a bug.

Bye
