### ISSUE TITLE
Rework of chat box style

### ISSUE THREAD

**Issue by lovelle** [lovelle/jquery-chat#9]
It would be good to have a more fancy and modern chat box window.
screen on how's it looks in the day of today:

![luke-box](https://cloud.githubusercontent.com/assets/7503370/7994060/e0bd0d28-0ae0-11e5-975d-3147162729c7.jpg)

TODO things that new style should have:

Features:
- [x] Textarea with some text like "Write here to send message..."
- [x] Show user email at some top bar on chat box.
- [x] [Gravatar](gravatar.com) support  - Fancy avatar emoticons, to see who you talking with.
- [x] Number of new messages received displayed on top bar
- [x] Better format of message date
- [x] Date displayed on each message must be performed by server date
- [x] Display user messages in some kind of bubble
- [x] Fancy scrollbar

Issues
- [x] Visual issue, when box increase his height must be done by upside, no downside.
- [x] inconsistency allowing multiple themes in chat box (visual issue)
- [x] correct handling in errors like "user allready logged"
- [x] Bug in firefox with textarea chat box

Any ideas are very welcome :+1:

**Comment by lovelle** [comment]
Just updating issue to see how it looks now.

![new-box-style](https://cloud.githubusercontent.com/assets/7503370/8194935/5944a918-1455-11e5-80f8-e1613f20e6c3.png)

**Comment by ghost** [comment]
do a css "resize:none;" for the message box

**Comment by lovelle** [comment]
There is no need to do that, this is already done by jquery ui Dialog api.

**Comment by lovelle** [comment]
Merged and working, also in demo page.

**Comment by lovelle** [comment]
Bug in firefox browser found, ASAP 'll be fixed

**Comment by lovelle** [comment]
Seems to be fixed last bug :+1:

**Comment by lovelle** [comment]
Issue done, closed.
